website:
  title:
    default: "TiDB.AI"
    data_type: str
    description: "The title of the website."
    client: true
  description:
    default: "Knowledge Graph based RAG that built with TiDB Serverless Vector Storage and LlamaIndex"
    data_type: str
    description: "The description of the website."
    client: true
  homepage_title:
    default: "Ask anything about TiDB"
    data_type: str
    description: "The title of the homepage."
    client: true
  homepage_example_questions:
    default:
      - "What is TiDB?"
      - "Does TiDB support FOREIGN KEY?"
      - "Does TiDB support serverless?"
    data_type: list
    description: "The example questions on the homepage."
    client: true
  homepage_footer_links:
    default:
      - text: "Release Notes"
        href: "https://tidb.ai/docs/changelog"
      - text: "Powered by TiDB Vector"
        href: "https://tidb.cloud/ai"
      - text: "Â© 2024 PingCAP"
        href: "https://pingcap.com"
    data_type: list
    description: "The footer links on the homepage."
    client: true
  logo_in_dark_mode:
    default: "https://tidb.ai/tidb-ai-light.svg"
    data_type: str
    description: "The logo in dark mode."
    client: true
  logo_in_light_mode:
    default: "https://tidb.ai/tidb-ai.svg"
    data_type: str
    description: "The logo in light mode."
    client: true
  social_github:
    default: "https://github.com/pingcap/tidb.ai"
    data_type: str
    description: "The link to the github"
    client: true
  social_twitter:
    default: "https://twitter.com/PingCAP"
    data_type: str
    description: "The link to the twitter"
    client: true
  social_discord:
    default: "https://discord.gg/XzSW23Jg9p"
    data_type: str
    description: "The link to the discord"
    client: true
  ga_id:
    default: ""
    data_type: str
    description: "Google Analytics ID"
    client: true

custom_js:
  custom_js_example_questions:
    default:
      - "What is TiDB?"
      - "Does TiDB support FOREIGN KEY?"
      - "Does TiDB support serverless?"
    data_type: list
    description: "The example questions on the custom_js."
    client: true
  custom_js_button_label:
    default: "Ask AI"
    data_type: str
    description: "The button label on the custom_js."
    client: true
  custom_js_button_img_src:
    default: "https://tidb.ai/tidb-ai.svg"
    data_type: str
    description: "The button image on the custom_js."
    client: true
  custom_js_logo_src:
    default: "https://tidb.ai/tidb-ai-light.svg"
    data_type: str
    description: "The logo on the custom_js."
    client: true

security:
  # TODO: recaptcha_site_secret?

  recaptcha_site_key:
    default: ""
    data_type: str
    description: "TODO"
    client: true

  recaptcha_enterprise_mode:
    default: false
    data_type: bool
    description: "TODO"
    client: true
